### PR TITLE
Updated stylings and no "aircraft type" for fla page

### PR DESCRIPTION
**Pull request by harry-bond**

### CODE REVIEW

**Comment by NexInfinite** [comment]
Sorry for delay, gonna look into this now

**Comment by NexInfinite** [comment]
image
Looks like the sizes are just a bit off, would be good if we could get them to be the same. I think everything would look a bit cleaner with a bit less padding and a slightly smaller font size - its not the main part of the page so shouldn't be the largest text.

Also if a file name is underlined its usually implied that it is clickable/interactable, in this case its underlined but no actions can be done it. To make it a bit clearer either don't underline it or pop open file explorer to its location on click.

**Comment by NexInfinite** [comment]
also would be nice if this gap was a bit smaller
image

**Comment by harry-bond** [comment]
I've corrected the styling to what we talked about, once again let me know if something looks off, never had an eye for this sort of thing.

image


I've also had a go at the file explorer thing that now works when clicked. However it does open a large window rather than a smaller one but apparently, from what I've read that can't be changed because of electron, its down the the operating system.

image

**Comment by NexInfinite** [comment]
Looking good, the file explorer is exactly what I was looking for. I added some rounding to the accordion just to make things look more cohesive. Will merge now

**Pull request merged**
